
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abwzezikbhlpmwbcovvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFid3plemlrYmhscG13YmNvdnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzg1MzQsImV4cCI6MjA2MjcxNDUzNH0.uH5TJILjc4IW4JvtGoztx8hzyFmZFoJlomODJdIEyO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  },
  global: {
    headers: {
      'x-application-name': 'voice-assistant'
    }
  }
});
